= Install https://www.raspberrypi.org/downloads/raspbian/[Raspbian] on an SD Card
BIGBen99
v20190126-001

This guide explains how to install Raspbian on an SD card with a computer based on Linux system.

== Prerequisites
1 microSD card over 8GB +
1 Computer with a SD card reader and an Internet connection +

== Installing Raspbian

=== Download the image archive file
You can find the official images of Raspbian in the https://www.raspberrypi.org/downloads/raspbian/[download section of the Raspberry Pi website]. Select the image you need and download it archive.

On Linux system, you can type in a terminal the command below to get the latest Raspbian lite image (Minimal image based on Debian without desktop and recommanded software).
....
$ wget https://downloads.raspberrypi.org/raspbian_lite_latest --output-document=raspbian_lite_latest.zip
....

=== Unzip to get the image
Unzip the file you downloaded to the image file (.img)
....
$ unzip raspbian_lite_latest.zip
....

=== Discovering the SD card mountpoint and unmounting it
List disk partition table to identify your SD card mountpoint
....
$ fdisk -l | grep "Dis.* /"
....

Unmount your SD card
....
$ umount /dev/SD_CARD_MOUNTPOINT*
....

=== Copying the image to the SD card

....
$ dd if=PATH_TO_THE_IMAGE_FILE of=DEVICE_NAME bs=4M status=progress conv=fsync
....

=== Enable SSH
SSH can be enabled by placing a file named ssh, without any extension, onto the boot partition of the SD card.

In a terminal, once you are located onto the boot partition, type the command below
....
$ touch ssh
....

== Conclusion
You now have a microSD card with the Raspbian operating system installed. Your SD card is ready to be used in a https://www.raspberrypi.org/products/[Raspberry Pi board]

== External links
https://www.raspberrypi.org/downloads/raspbian/[Raspbian]
